from typing import Final
class ServerConstants:
    ARGS: Final = "args"
    DEBUG_MODE: Final = "debug_mode"
    FUNC: Final = "func"
    TENSORS: Final = "tensors"
    MODEL_ID: Final = "model_id"
    DTYPE: Final = "dtype"
    SHAPE: Final = "shape"
    DATA_K: Final = "data_k"
    DEVICE: Final = "device"
    CHECKPOINT_NAME: Final = "checkpoint_name"
    CHECKPOINT_PATH: Final = "checkpoint_path"
    TENSORBOARD_LOG_PATH: Final = "tensorboard_log_path"

    NONE: Final = "None"
    PORT: Final = "5000"

    CLIP_PARAM: Final = "clip_param"
    VALUE_LOSS_COEF: Final = "value_loss_coef"
    ENTROPY_COEF: Final = "entropy_coef"
    MAX_GRAD_NORM: Final = "max_grad_norm"
    OPTIMIZER_EPSILON: Final = "optimizer_epsilon"
    LR_DECAY: Final = "lr_decay"
    LR_DECAY_STEPS: Final = "lr_decay_steps"
    MIN_LR: Final = "min_lr"
    KL_TARGET: Final = "kl_target"
    KL_COEFFICIENT: Final = "kl_coefficient"
    EPOCHS: Final = "epochs"
    BATCH_SIZE: Final = "batch_size"
    LEARNING_RATE: Final = "learning_rate"
    OUT_DIM: Final = "out_dim"
    N_HEADS: Final = "n_heads"
    SEED: Final = "seed"
    IN_DIM_FEAT_DFG: Final = "in_dim_feat_dfg"
    IN_DIM_FEAT_CGRA: Final = "in_dim_feat_cgra"
